[Connection]
host = 127.0.0.1
port = 6600

[Library]
music_dir = @@HOME@@/Musik
cover_regex = ^(album|cover|\.?folder|front).*\.(gif|jpeg|jpg|png)$

[Bling]
mmkeys = False
notify = False
notify_urgency = 0
