# Warehouse-13 Lesbian Cyberpunk
foreground            #f6d9d8
background            #05020b
selection_foreground  #fff0ef
selection_background  #520535

cursor                 #ee0f54
cursor_text_color      #05020b
url_color              #dc2683

active_border_color    #ee0f54
inactive_border_color  #520535
bell_border_color      #ff4d6d

active_tab_foreground    #05020b
active_tab_background    #ee0f54
inactive_tab_foreground  #d9a8be
inactive_tab_background  #120a19
tab_bar_background       #05020b

color0   #0b0516
color1   #ff4d6d
color2   #5de4a3
color3   #f5b56b
color4   #7c6cff
color5   #dc2683
color6   #54d6e8
color7   #d9a8be
color8   #6a4060
color9   #ff7396
color10  #82f0bb
color11  #ffd093
color12  #a698ff
color13  #f05ba8
color14  #83e7f3
color15  #fff0ef
